#!/bin/bash

#filef="test.test.test"
#fileff=$(basename -- "$filef" .test)
#outdir=$(dirname -- "$filef")
#echo "${outdir}/${fileff}.best"
#exit 0
llf=$(mktemp /tmp/llf.XXXXXX)
basefile=$(basename -- "$1" .lat)
outdir=$(dirname -- "$1")
interf="${outdir}/${basefile}.ll"
src/haskellsrc/Main "$1" > "$llf" && src/csrc/build/compiler < "$llf" > "$interf" || (error=$? ; rm "$llf" ; rm "$interf" ; exit $error)


bcf=$(mktemp /tmp/bcf.XXXXXX)
linkf="${outdir}/${basefile}.bc"


llvm-as -o "$bcf" "$interf"
llvm-link -o "$linkf" "$bcf" "lib/runtime.bc"
error=$?

rm "$llf"
rm "$bcf"
exit $error