#!/bin/bash

treef=$(mktemp /tmp/treef.XXXXXX)

basefile=$(basename -- "$1" .lat)

outdir=$(dirname -- "$1")

src/haskellsrc/Main "$1" > "$treef"
flag=$?
if [ $flag -ne 0 ]; then
  rm "$treef"
  exit $flag
else
  llf="${outdir}/${basefile}.ll"
  src/csrc/build/compiler < "$treef" > "$llf"
  flag=$?
  rm "$treef"
fi

if [ $flag -ne 0 ]; then
  rm "$llf"
  exit $flag
else
  bcf=$(mktemp /tmp/bcf.XXXXXX)
  llvm-as -o "$bcf" "$llf"
  flag=$?
fi

if [ $flag -ne 0 ]; then
  rm "$llf"
  rm "$bcf"
  exit $flag
else
  resf="${outdir}/${basefile}.bc"
  llvm-link -o "$resf" "$bcf" "lib/runtime.bc"
  flag=$?
fi

rm "$bcf"
exit $flag