

int main() {
    int x = 0;
    if(x+1 != add_one(x)) {
        return -1;
    }
    string s1 = "Hello ";
    string s2 = "world\n";
    if(concat(s1,s2) != "Hello world\n") {
        return -1;
    }
    bool b = false;
    if(!b != not(b)) {
        return -1;
    }
    int[][] arr = new int[7][7];
    int i = 0;
    while(i < arr::LENGTH) {
        int j = 0;
        while(j < arr[i]::LENGTH) {
            arr[i][j] = i+j;
            print << arr[i][j] << " ";
            j = j+1;
        }
        i=i+1;
    }
    print << "\n";
    int[][] arr2 = add_one_to_all(arr);
    return 0;
}


int add_one(int x) {
    return x+1;
}

string concat(string s1, string s2) {
    return s1 + s2;
}

bool not(bool b) {
    return !b;
}

int[][] add_one_to_all(int[][] arr) {
    int i = 0;
    while(i < arr::LENGTH) {
        int j = 0;
        while(j < arr[i]::LENGTH) {
            arr[i][j] = arr[i][j]+1;
            print << arr[i][j] << " ";
            j = j+1;
        }
        i=i+1;
    }
    print << "\n";
    return arr;
}