#!/bin/bash

src/haskellsrc/Main "$1" > "tmp/test.tree"
flag=$?
if [ $flag -ne 0 ]; then
  rm "tmp/test.tree"
  exit $flag
else
  src/csrc/build/compiler < "tmp/test.tree" > "tmp/test.ll"
  flag=$?
  rm "tmp/test.tree"
fi

if [ $flag -ne 0 ]; then
  rm "tmp/test.ll"
  exit $flag
else
  llvm-as -o "tmp/test.bc" "tmp/test.ll"
  flag=$?
fi

if [ $flag -ne 0 ]; then
  rm "tmp/test.ll"
  rm "tmp/test.bc"
  exit $flag
else
  llvm-link -o "tmp/run.bc" "tmp/test.bc" "lib/runtime.bc"
  flag=$?
fi

rm "tmp/test.bc"
exit $flag